version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: univibe-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: univibe
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_univibe123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
